#!/usr/bin/env python3
"""Validate and stage the uploaded release zip for the Android build.

The zip must contain:

  1. The game library - ``lib/arm64-v8a/libnfsmw.so`` (any
     ``lib/<abi>/libnfsmw.so`` or a ``libnfsmw.so`` at the zip root also
     works). It must be an ELF64 little-endian aarch64 shared object.
  2. The game files - a top-level ``game/`` directory (an ``assets/``
     directory or loose top-level directories work too). This is the game
     directory the kit stages, i.e. your installation minus
     ``[bundle].exclude`` from game.toml.

With ``--stage DIR`` (DIR = the app's src/main) the tool copies

  <library>     -> DIR/jniLibs/arm64-v8a/libnfsmw.so
  <game files>  -> DIR/assets/game/...

and writes ``DIR/java/dev/recompkit/nfsmw/android/BuildInfo.kt`` plus
``DIR/assets/game/.manifest.json``.

Exit codes: 0 valid (and staged, when asked), 2 invalid zip, 3 usage error.
"""
import argparse
import hashlib
import json
import os
import sys
import zipfile


LIB_NAME = "libnfsmw.so"
PKG_DIR = os.path.join("java", "dev", "recompkit", "nfsmw", "android")
SKIP_TOP_LEVEL = {
    "readme.md", "readme.txt", "manifest.json", "manifest.txt", ".gitkeep",
}

BUILDINFO_TEMPLATE = '''// Generated by tools/android/validate_zip.py - do not edit by hand.
package dev.recompkit_nfsmw.android

object BuildInfo {{
    const val VERSION_NAME = "{version}"
    const val BUILD_ID = "{build_id}"
    const val ASSET_SHA = "{asset_sha}"
    const val ASSET_COUNT = {asset_count}
    const val ASSET_BYTES = {asset_bytes}L
    const val LIB_SHA = "{lib_sha}"
    const val SOURCE_URL = "{source_url}"
    const val BUILT_AT = "{built_at}"

    val hasGame: Boolean get() = LIB_SHA.isNotEmpty()
    val hasAssets: Boolean get() = ASSET_COUNT > 0
    val isReleaseBuild: Boolean get() = BUILD_ID != "dev"
}}
'''


def die(msg, code=2):
    print("ERROR: " + msg, file=sys.stderr)
    print("See docs/android.md for the zip layout.", file=sys.stderr)
    sys.exit(code)


def sha256_stream(fh, chunk=1 << 20):
    h = hashlib.sha256()
    while True:
        b = fh.read(chunk)
        if not b:
            break
        h.update(b)
    return h.hexdigest()


def classify_elf(head: bytes) -> str:
    """Classify the first 64 bytes of a binary: aarch64, arm32, elf-other, not-elf."""
    if len(head) < 20 or head[:4] != b"\x7fELF":
        return "not-elf"
    ei_class, ei_data = head[4], head[5]
    e_machine = head[18:20]
    if e_machine == b"\xb7\x00" and ei_class == 2 and ei_data == 1:
        return "aarch64"
    if e_machine == b"\x28\x00" and ei_class == 1 and ei_data == 1:
        return "arm32"
    return "elf-other"


def find_lib(zf: zipfile.ZipFile):
    """The zip entry for the game library, or None. Prefers lib/arm64-v8a/."""
    cands = [n for n in zf.namelist() if not n.endswith("/") and n.split("/")[-1] == LIB_NAME]
    if not cands:
        return None

    def rank(n):
        parts = n.split("/")
        if "arm64-v8a" in parts:
            return 0
        if parts[0] == "lib":
            return 1
        if len(parts) == 1:
            return 2
        return 3

    return sorted(cands, key=rank)[0]


def is_dir_entry(zf: zipfile.ZipFile, top: str) -> bool:
    prefix = top + "/"
    return any(n == top + "/" or n.startswith(prefix) for n in zf.namelist())


def find_game(zf: zipfile.ZipFile, lib_path: str):
    """Game file entries as (zip_name, rel_path_in_apk). The library and
    stray top-level text/manifest files are not game files."""
    lib_top = lib_path.split("/")[0] if "/" in lib_path else None
    tops = {}
    for n in zf.namelist():
        if n.endswith("/"):
            tops.setdefault(n.split("/")[0], "dir")
            continue
        top = n.split("/")[0]
        if top not in tops:
            tops[top] = "dir" if is_dir_entry(zf, top) else "file"

    game_dirs = []
    for top, kind in sorted(tops.items()):
        if kind != "dir":
            continue
        if top == lib_top:
            continue
        game_dirs.append(top)

    entries = []
    if game_dirs:
        for d in game_dirs:
            prefix = d + "/"
            for n in zf.namelist():
                if n.startswith(prefix):
                    rel = n[len(prefix):] if len(game_dirs) == 1 else n
                    entries.append((n, rel))
    else:
        # No game directory: loose top-level files (minus the library itself).
        lib_base = lib_path.split("/")[-1]
        for top, kind in sorted(tops.items()):
            if kind != "file" or top == lib_top or top == lib_base:
                continue
            if top.lower() in SKIP_TOP_LEVEL:
                continue
            entries.append((top, top))
    return entries


def copy_entry(zf: zipfile.ZipFile, name: str, out_path: str) -> str:
    """Stream one zip entry to disk; returns its sha256."""
    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    h = hashlib.sha256()
    with zf.open(name) as src, open(out_path, "wb") as dst:
        while True:
            b = src.read(1 << 20)
            if not b:
                break
            h.update(b)
            dst.write(b)
    return h.hexdigest()


def kotlin_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("zip_path", help="path to the uploaded zip")
    ap.add_argument("--stage", metavar="SRC_MAIN",
                    help="stage the library and game files into this src/main directory")
    ap.add_argument("--report", metavar="FILE", help="write the JSON report here")
    ap.add_argument("--version-name", default="0.0.0")
    ap.add_argument("--source-url", default="")
    ap.add_argument("--built-at", default="")
    args = ap.parse_args()

    if not os.path.isfile(args.zip_path):
        die("zip not found: " + args.zip_path, 3)
    try:
        zf = zipfile.ZipFile(args.zip_path)
    except zipfile.BadZipFile as e:
        die("not a valid zip archive: " + str(e))
    bad = zf.testzip()
    if bad is not None:
        die("corrupt entry in the zip: " + bad)

    file_names = [n for n in zf.namelist() if not n.endswith("/")]
    if not file_names:
        die("the zip is empty")

    lib_path = find_lib(zf)
    if lib_path is None:
        die("the zip does not contain " + LIB_NAME +
            ". Expected lib/arm64-v8a/" + LIB_NAME + " - the recompiled game library.")
    with zf.open(lib_path) as fh:
        kind = classify_elf(fh.read(64))
    if kind == "not-elf":
        die(lib_path + " is not an ELF binary - is that the recompiled game library?")
    if kind != "aarch64":
        die(lib_path + " is a " + kind + " binary; the Android build requires an "
            "aarch64 (arm64-v8a) shared object. Rebuild the game for Android.")

    game_entries = find_game(zf, lib_path)
    if not game_entries:
        die("the zip contains only the library - where are the game files? "
            "Put them under a top-level game/ directory (see docs/android.md).")

    sizes = [zf.getinfo(n).file_size for n, _ in game_entries]
    total = sum(sizes)
    exts = {}
    for _, rel in game_entries:
        ext = os.path.splitext(rel)[1].lower() or "(none)"
        exts[ext] = exts.get(ext, 0) + 1
    warnings = []
    if total < 50 * 1024 * 1024:
        warnings.append("the game directory is only %d MB; a full install is over 1 GB"
                        % (total // (1024 * 1024)))
    for need in ("SOUND", "TRACKS", "GLOBAL"):
        if not any(rel.split("/")[0].upper() == need for _, rel in game_entries):
            warnings.append("no %s/ directory in the game files" % need)

    zip_sha = sha256_stream(open(args.zip_path, "rb"))

    report = {
        "zip": os.path.abspath(args.zip_path),
        "zip_size": os.path.getsize(args.zip_path),
        "lib": {"path": lib_path, "size": zf.getinfo(lib_path).file_size},
        "game": {
            "file_count": len(game_entries),
            "total_bytes": total,
            "top_extensions": dict(sorted(exts.items(), key=lambda kv: -kv[1])[:12]),
        },
        "warnings": warnings,
    }

    if args.stage:
        src = args.stage
        # Re-staging must not leave files from an earlier build behind.
        jni = os.path.join(src, "jniLibs", "arm64-v8a")
        assets = os.path.join(src, "assets", "game")
        import shutil
        if os.path.isdir(jni):
            shutil.rmtree(jni)
        if os.path.isdir(assets):
            shutil.rmtree(assets)

        lib_out = os.path.join(jni, LIB_NAME)
        lib_sha = copy_entry(zf, lib_path, lib_out)

        per_file = []
        for n, rel in game_entries:
            fsha = copy_entry(zf, n, os.path.join(assets, rel))
            per_file.append((rel, os.path.getsize(os.path.join(assets, rel)), fsha))
        per_file.sort()
        tree = hashlib.sha256(
            "\n".join("%s|%d|%s" % (r, s, h) for r, s, h in per_file).encode("utf-8")
        ).hexdigest()
        manifest = {
            "schema": 1,
            "asset_sha": tree,
            "file_count": len(per_file),
            "total_bytes": sum(s for _, s, _ in per_file),
        }
        with open(os.path.join(assets, ".manifest.json"), "w") as f:
            json.dump(manifest, f, indent=2)

        buildinfo = BUILDINFO_TEMPLATE.format(
            version=kotlin_escape(args.version_name),
            build_id=zip_sha[:12],
            asset_sha=tree,
            asset_count=len(per_file),
            asset_bytes=sum(s for _, s, _ in per_file),
            lib_sha=lib_sha,
            source_url=kotlin_escape(args.source_url),
            built_at=kotlin_escape(args.built_at),
        )
        bi_dir = os.path.join(src, PKG_DIR)
        os.makedirs(bi_dir, exist_ok=True)
        with open(os.path.join(bi_dir, "BuildInfo.kt"), "w") as f:
            f.write(buildinfo)
        report["shas"] = {"zip": zip_sha, "lib": lib_sha, "assets": tree}
        report["staged_into"] = os.path.abspath(src)

    if args.report:
        with open(args.report, "w") as f:
            json.dump(report, f, indent=2)

    print("## Zip validation report")
    print("zip          : %s (%d MB)" % (report["zip"], report["zip_size"] // (1024 * 1024)))
    print("library      : %s (%d bytes, %s)" % (lib_path, report["lib"]["size"], kind))
    print("game files   : %d files, %d MB" % (report["game"]["file_count"],
                                               report["game"]["total_bytes"] // (1024 * 1024)))
    print("extensions   : %s" % ", ".join("%s x%d" % kv for kv in
                                          list(report["game"]["top_extensions"].items())[:8]))
    for w in warnings:
        print("warning      : " + w)
    if args.stage:
        print("staged into  : " + report.get("staged_into", ""))
    print("## REPORT_JSON")
    print(json.dumps(report))
    sys.exit(0)


if __name__ == "__main__":
    main()
